import os
import shutil


def move(file, folder):
    print("[+] Moving {} to {}".format(file, folder))
    shutil.move(file, folder)


def file_folder():
    credit()
    files = os.listdir()
    for i in files:
        extension = i.split(".")[-1]
        if (i == "file_mover.py") or (i == "file_mover.exe"):
            continue
        try:
            os.mkdir(extension)
            move(i, extension)
        except:
            print("[~] {} already existed".format(extension))
            move(i, extension)


def credit():
    print("""
           Automatic file sorter using extension
           """)
    print("""

 ██▀███   ▄▄▄       ██░ ██  █    ██  ██▓    
▓██ ▒ ██▒▒████▄    ▓██░ ██▒ ██  ▓██▒▓██▒    
▓██ ░▄█ ▒▒██  ▀█▄  ▒██▀▀██░▓██  ▒██░▒██░    
▒██▀▀█▄  ░██▄▄▄▄██ ░▓█ ░██ ▓▓█  ░██░▒██░    
░██▓ ▒██▒ ▓█   ▓██▒░▓█▒░██▓▒▒█████▓ ░██████▒
░ ▒▓ ░▒▓░ ▒▒   ▓▒█░ ▒ ░░▒░▒░▒▓▒ ▒ ▒ ░ ▒░▓  ░
  ░▒ ░ ▒░  ▒   ▒▒ ░ ▒ ░▒░ ░░░▒░ ░ ░ ░ ░ ▒  ░
  ░░   ░   ░   ▒    ░  ░░ ░ ░░░ ░ ░   ░ ░   
   ░           ░  ░ ░  ░  ░   ░         ░  ░ code generated by Rahul.p

""")

try:
    file_folder()
except:
    print("[-] Exiting....")