from glob import iglob
from os import mkdir
from os.path import exists,splitext,isfile
from shutil import move
from colorama import Fore, init, Style

bright = Style.BRIGHT
green, blue, red, cyan, reset = Fore.GREEN + bright, Fore.BLUE + bright, Fore.RED + bright, Fore.CYAN, Fore.RESET
init(convert=True, autoreset=True)

def process(filename):
    if isfile(filename):
        _,file_extension = splitext(filename)
        if file_extension:
            file_extension = file_extension[1:]
            if not exists(f'main_folder/{file_extension}'):
                mkdir(f'main_folder/{file_extension}')
            try:
                move(filename,f'main_folder/{file_extension}')
            except Exception:
                if not exists(f'already_exsisted/{file_extension}'):
                    mkdir(f'already_exsisted/{file_extension}')
                move(filename,f'already_exsisted/{file_extension}')

def credit():
    credit_text = f"""
               {red}AUTOMATIC FILE SORTER USING EXTENSION
{green}               
     ██▀███   ▄▄▄       ██░ ██  █    ██  ██▓    
    ▓██ ▒ ██▒▒████▄    ▓██░ ██▒ ██  ▓██▒▓██▒    
    ▓██ ░▄█ ▒▒██  ▀█▄  ▒██▀▀██░▓██  ▒██░▒██░    
    ▒██▀▀█▄  ░██▄▄▄▄██ ░▓█ ░██ ▓▓█  ░██░▒██░    
    ░██▓ ▒██▒ ▓█   ▓██▒░▓█▒░██▓▒▒█████▓ ░██████▒
    ░ ▒▓ ░▒▓░ ▒▒   ▓▒█░ ▒ ░░▒░▒░▒▓▒ ▒ ▒ ░ ▒░▓  ░
      ░▒ ░ ▒░  ▒   ▒▒ ░ ▒ ░▒░ ░░░▒░ ░ ░ ░ ░ ▒  ░
      ░░   ░   ░   ▒    ░  ░░ ░ ░░░ ░ ░   ░ ░   
       ░           ░  ░ ░  ░  ░   ░         ░  ░ {blue}code generated by Rahul.p\n
    """
    print(credit_text)

credit()

[mkdir(folder) for folder in ["main_folder", "already_exsisted"] if not exists(folder)]

path = input("[+] Enter path or drag and drop the folder : ").replace('"','')

if path=='':
    path = input("[+] Enter path or drag and drop the folder : ").replace('"','')

for filename in iglob(f'{path}/**/*',recursive=True):
    print(f"{green}[+] Processing file - {filename}")
    try:
        process(filename)
    except Exception as e:
        print(f"{red}[-] Error - {e}")
        continue

input("[-] Press any key to close")