from os import listdir, mkdir, walk, getcwd
from os.path import exists, splitext
from shutil import move


def folder_files_list(dirpath):
    files = listdir(dirpath)
    for file in files:
        if file == 'file_extension_sorter.py':
            continue
        name, extension = splitext(file)
        extension = extension[1:]
        if extension == '':
            continue
        folder_make(dirpath, file, extension)


def folder_list():
    folder = input("[+] Enter folder name or drag and drop :- ")
    for (dirpath, dirnames, filenames) in walk(folder):
        print("[+] processing the folder :- ", dirpath)
        folder_files_list(dirpath)


def file_move(dirpath, file, extension):
    print("[+] moving file:-  {} to folder {}".format(file, extension))
    move(dirpath + '/' + file, dirpath + '/' + extension + '/' + file)


def folder_make(dirpath, file, extension):
    try:
        if exists(dirpath + '/' + extension):
            file_move(dirpath, file, extension)
        else:
            mkdir(dirpath + '/' + extension)
            file_move(dirpath, file, extension)
    except:
        print("[-] Folder make error occur")


def credit():
    print("""
           Automatic file sorter using extension
           """)
    print("""

 ██▀███   ▄▄▄       ██░ ██  █    ██  ██▓    
▓██ ▒ ██▒▒████▄    ▓██░ ██▒ ██  ▓██▒▓██▒    
▓██ ░▄█ ▒▒██  ▀█▄  ▒██▀▀██░▓██  ▒██░▒██░    
▒██▀▀█▄  ░██▄▄▄▄██ ░▓█ ░██ ▓▓█  ░██░▒██░    
░██▓ ▒██▒ ▓█   ▓██▒░▓█▒░██▓▒▒█████▓ ░██████▒
░ ▒▓ ░▒▓░ ▒▒   ▓▒█░ ▒ ░░▒░▒░▒▓▒ ▒ ▒ ░ ▒░▓  ░
  ░▒ ░ ▒░  ▒   ▒▒ ░ ▒ ░▒░ ░░░▒░ ░ ░ ░ ░ ▒  ░
  ░░   ░   ░   ▒    ░  ░░ ░ ░░░ ░ ░   ░ ░   
   ░           ░  ░ ░  ░  ░   ░         ░  ░ code generated by Rahul.p

""")


credit()
try:
    menu = input("[*] Do you want to process folder press 'y' or "
                 "'n' to process files in current directory :- ")
    if menu == 'y':
        folder_list()
    elif menu == 'n':
        folder_files_list(getcwd())
except:
    print("[-] Exiting....")
